server:
  port: 8081
  servlet:
    context-path: /api/v1

# JWT 관련 설정
jwt:
  private-key-path: classpath:/keys/private.pem
  public-key-path: classpath:/keys/public.pem
  access-token-ttl-sec: 3600        # 1시간
  refresh-token-ttl-sec: 1209600    # 14일
  issuer: auth-server
